server:
  port: 10086
spring:
  application:
    name: zcloud
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names: ''
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    #引用项目中的数据库文件
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:static/sqlite/zcloud.db
    username: root
    password: root

  flyway:
    enabled: false
    clean-disabled: false


  redis:
    database: 0
    host: 106.52.82.52
    port: 6379
    password: Aa12345678

  security:
    user:
      name: admin
      password: admin
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    #设置空如何序列化
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true

#          @Value("${default.admin.username}")
      #    public static String DEFAULT_ADMIN_USERNAME;
      #
      #    @Value("${default.admin.password}")
      #    public static String DEFAULT_ADMIN_PASSWORD;
      #
      #    @Value("${global.other.admins}")
      #    public static List GLOBAL_OTHER_ADMINS;

default:
  admin:
    username: admin
    password: admin

global:
  other-admin:
    - username: test1
      password: test1
    - username: test2
      password: test2
